### ISSUE TITLE
Errore 500 in fase di generazione del metadata

### ISSUE THREAD

**Issue by opetrone** [italia/spid-php#64]
Ho installato il pacchetto sul mio server con successo. Quando provo a generare il metadata all'url miodominio.it/simplesaml/module.php/saml/sp/metadata.php/service il server mi restituisdce un errore 500.
Verificando nel file di log di Apache, rilevo il seguente errore:
[Tue Feb 09 17:45:57.679673 2021] Got error 'PHP message: PHP Fatal error:  Uncaught SimpleSAML_Error_AuthSource: Error with authentication source 'service': Unknown authentication source. in /home/adminserver/spid-php/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Auth/Simple.php:58\nStack trace:\n#0 /home/adminserver/spid-php/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Auth/Simple.php(160): SimpleSAML\\Auth\\Simple->getAuthSource()\n#1 /home/adminserver/spid-php/spid-php.php(65): SimpleSAML\\Auth\\Simple->login(Array)\n#2 /var/www/html/public/test_spid/login-spid.php(27): SPID_PHP->login('TEST', 2)\n#3 {main}\n  thrown in /home/adminserver/spid-php/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Auth/Simple.php on line 58\n', referer: https://miodominio.it/test_spid/login-spid.php
Quale potrebbe essere la causa? nel file authsource la fonte service c'è e mi sembra che sia impostata correttamente.

**Comment by opetrone** [comment]
risolto, c'era un conflitto con un'altra istanza di simplesaml presente sul server
